language: ruby
rvm:
  - 2.1.0
env:
  - DB=postgresql
script:
  - RAKE_ENV=test rake db:drop db:create db:migrate db:test:prepare
  - bundle exec rspec .
before_script:
  - psql -c 'create database cc_test' -U pruett
