test:
  adapter: postgresql
  encoding: unicode
  database: cc_test
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: cc_development
  pool: 5
  username: pruett
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: cc_production
  pool: 5
  username: pruett
  password:
