development: &defaults
  adapter: postgresql
  database: cc_dev
  encoding: unicode
  pool: 5
  username: pruett
  password: ""

test:
  <<: *defaults
  database: cc_test

production:
  <<: *defaults
  database: cc_production
